### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [allansrc/Catalina-macOS-Aspire-5#2]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by allansrc** [comment]
to ajust bright you can use fn+arrow key left/right, also fn+f12/pause

**Comment by allansrc** [comment]
to modify theses keys you can use the follow link: [here](https://www.insanelymac.com/forum/topic/330440-beginners-guide-fix-keyboard-hot-keys-functional-keys/)

**Comment by marcinkk** [comment]
I understand, but how do you set the keys fn + left / right arrow ??  Because they do not currently support screen brightness adjustment.

**Comment by allansrc** [comment]
> I understand, but how do you set the keys fn + left / right arrow ?? Because they do not currently support screen brightness adjustment.

https://www.insanelymac.com/forum/topic/330440-beginners-guide-fix-keyboard-hot-keys-functional-keys/

follow the link to manual set it [hot key set](https://www.insanelymac.com/forum/topic/330440-beginners-guide-fix-keyboard-hot-keys-functional-keys/)
